### ISSUE TITLE
Fail to setup

### ISSUE THREAD

**Issue by shervinsafavi** [gcentauri/xah-fly-keys-layer#1]
Hi, 

First of all, many thanks for putting effort to make it! 

I tried to set it up, by following your instruction, but when I run emacs, I face with the following warning: "Unknown layer xah-fly-keys declared in your dotfile".

Do you have any idea why did it happen? Or any hint?

(I'm very new to emacs)

**Comment by gcentauri** [comment]
Hi @shervinsafavi ! 

Assuming you cloned this repository into `~/.emacs.d/private/xah-fly-keys` i think it should detect the layer.  To be honest, I moved to integrate the package in my fork of Spacemacs and haven't updated this in a while.  I'm happy to help you figure it out, its possible I need to update this repository.

**Comment by shervinsafavi** [comment]
Of course I cloned it in the path you suggest. 
So, I will check your cloned version, maybe I figure it out ;) In case you find a clue please let me know :)

**Comment by gcentauri** [comment]
@shervinsafavi - well I just installed it myself as a private layer and it worked for me.  does the file `~/.emacs.d/private/xah-fly-keys/packages.el` exist?  Spacemacs will look for that when loading layers, so if it is missing or in the wrong spot, then the layer will not load properly.

If you check out my fork, the commit is at the tip of the `develop` branch - https://github.com/gcentauri/spacemacs/commit/e18afcef0d0b1ed6d3dba7f82014add2628c7846

**Comment by shervinsafavi** [comment]
Solved :-) I understood the instruction as clone it inside this directory '.emacs.d/private/xah-fly-keys' and after cloning the repo, it will create another folder inside it and name it "xah-fly-keys-layer". One should clone the repo here '.emacs.d/private/' (or where ever private stuff are located) and the rename it to "xah-fly-keys" (maybe there is command to clone it and rename the folder but I don't know). Then if one follow the rest of your instructions, stuff will work (on the Ubuntu machine I tried, it complained about the colors, but that should not be an issue).

Feel free to close the issue then ;-) 
(if you think the instruction can be clearer and want to me modify the readme file please let me know)

**Comment by gcentauri** [comment]
If you want to take the time to improve the readme I'd be happy to accept it. I should probably keep maintaining this here since it will probably be some time before this layer is merged in Spacemacs officially. 

Please feel free to open issues and let me know what could work better! I don't know many people using both xah-fly-keys and Spacemacs so any input is helpful.

**Comment by shervinsafavi** [comment]
Sure, I'll make the changes and push them and sure when ever needed I open new issue (although I'm still using emacs on a daily basis and experimenting with spacemacs).
